package signswig;
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.33
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public interface signConstants {
  public final static int MAX_RADIUS = signJNI.MAX_RADIUS_get();
  public final static int MAX_L2W_RATIO = signJNI.MAX_L2W_RATIO_get();
  public final static int N_POINTS_MIN = signJNI.N_POINTS_MIN_get();
  public final static double LOG_ZERO = signJNI.LOG_ZERO_get();
  public final static double PRO_MIN_VAL = signJNI.PRO_MIN_VAL_get();
  public final static int COV_DIAG = signJNI.COV_DIAG_get();
  public final static int COV_FULL = signJNI.COV_FULL_get();
  public final static int PARAMETER_STANDARD_VARIATION = signJNI.PARAMETER_STANDARD_VARIATION_get();
  public final static int MAX_ITER_HMM = signJNI.MAX_ITER_HMM_get();
  public final static double END_ACCURACY = signJNI.END_ACCURACY_get();
  public final static int END_ITERATION_NUMBER = signJNI.END_ITERATION_NUMBER_get();
  public final static int TRANS_LR = signJNI.TRANS_LR_get();
  public final static int TRANS_BAKIS = signJNI.TRANS_BAKIS_get();
  public final static int TRANS_ERGODIC = signJNI.TRANS_ERGODIC_get();
}
